# References:
# https://gitlab.com/gitlab-org/gitlab-ci-yml/blob/master/Maven.gitlab-ci.yml
# https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html

image: bellsoft/liberica-openjdk-alpine:17

variables:
  MAVEN_OPTS: "--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED \
    --add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED \
    --add-exports=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED \
    --add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED \
    --add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED"
  MAVEN_CLI_OPTS: "--show-version \
    --batch-mode \
    --no-transfer-progress \
    -Duser.timezone=Asia/Jakarta \
    -Dhttps.protocols=TLSv1.2 \
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository \
    -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN \
    -Dorg.slf4j.simpleLogger.showDateTime=true \
    -Djava.awt.headless=true"
  RELEASE_DIGIT: 1
  HOTFIX_DIGIT: 2

cache:
  paths:
    - .m2/repository/

.git_setup_template: &git_setup
  - apk add --update --no-cache git
  - git --version
  - git remote set-url --push origin "https://${GITLAB_USER_LOGIN}:${READ_WRITE_REPOSITORY_ACCESS_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"
  - git config user.name "${GITLAB_USER_NAME}"
  - git config user.email "${GITLAB_USER_EMAIL}"

stages:
  - build
  - test
  - release

build:
  stage: build
  script:
    - *git_setup
    - ./mvnw $MAVEN_CLI_OPTS spotless:check pmd:check test-compile -U
  allow_failure: false
  except:
    - master
    - tags

test:
  variables:
    JACOCO_REPORT_HTML: $CI_PROJECT_DIR/target/site/jacoco/index.html
  stage: test
  script:
    - *git_setup
    - ./mvnw $MAVEN_CLI_OPTS verify -U
    - if [ -f $JACOCO_REPORT_HTML ]; then cat $JACOCO_REPORT_HTML | grep -o "Total[^%]*%"; fi
  allow_failure: false
  coverage: "/Total.*?([0-9]{1,3})%/"
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
  except:
    - master
    - tags

release:
  stage: release
  dependencies:
    - test
  script:
    - *git_setup
    - ./mvnw $MAVEN_CLI_OPTS gitflow:release -DversionDigitToIncrement=$RELEASE_DIGIT -DargLine=$MAVEN_CLI_OPTS
  only:
    - develop
  when: manual

hotfix-start:
  stage: release
  dependencies:
    - release
  script:
    - *git_setup
    - ./mvnw $MAVEN_CLI_OPTS gitflow:hotfix-start -DhotfixVersionDigitToIncrement=$HOTFIX_DIGIT -DargLine=$MAVEN_CLI_OPTS
    - git push origin HEAD
  only:
    - master
  when: manual

# Inspired from here: https://github.com/viesure/blog-gitflow-maven/blob/master/.gitlab-ci.yml
hotfix-finish:
  stage: release
  dependencies:
    - hotfix-start
  script:
    - *git_setup
    # Manually fix the git refs. gitflow plugin uses the heads ref, but we do not have it set up locally, however we have the remote ref
    - git symbolic-ref refs/heads/$CI_COMMIT_BRANCH refs/remotes/origin/$CI_COMMIT_BRANCH
    - ./mvnw $MAVEN_CLI_OPTS gitflow:hotfix-finish -DskipMergeDevBranch -DhotfixBranch=$CI_COMMIT_BRANCH -DargLine=$MAVEN_CLI_OPTS
  only:
    - /^hotfix\/.*$/
  when: manual
