# References:
# https://gitlab.com/gitlab-org/gitlab-ci-yml/blob/master/Maven.gitlab-ci.yml
# https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html

image: amazoncorretto:17-alpine

variables:
  MAVEN_OPTS: "--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED \
    --add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED \
    --add-exports=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED \
    --add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED \
    --add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED"
  MAVEN_CLI_OPTS: "--show-version \
    --batch-mode \
    --no-transfer-progress \
    -Duser.timezone=Asia/Jakarta \
    -Dhttps.protocols=TLSv1.2 \
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository \
    -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN \
    -Dorg.slf4j.simpleLogger.showDateTime=true \
    -Djava.awt.headless=true"
  RELEASE_DIGIT: 1
  HOTFIX_DIGIT: 2

.setup_git: &setup_git
  - git remote set-url --push origin "https://${GITLAB_USER_LOGIN}:${READ_WRITE_REPOSITORY_ACCESS_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"
  - git config user.name "${GITLAB_USER_NAME}"
  - git config user.email "${GITLAB_USER_EMAIL}"

.setup_alpine: &setup_alpine
  - apk add --update --no-cache maven git binutils lftp curl

.setup_debian: &setup_debian
  - apt-get update; apt-get install -y git binutils lftp curl sudo wget gpg
  - wget -O - https://apt.corretto.aws/corretto.key | gpg --dearmor -o /usr/share/keyrings/corretto-keyring.gpg
  - echo "deb [signed-by=/usr/share/keyrings/corretto-keyring.gpg] https://apt.corretto.aws stable main" | tee /etc/apt/sources.list.d/corretto.list
  - apt-get update; apt-get install -y java-17-amazon-corretto-jdk maven

cache:
  paths:
    - .m2/repository/

stages:
  - validate
  - test
  - release
  - publish-snapshot
  - publish-release

validate:
  stage: validate
  script:
    - *setup_alpine
    - *setup_git
    - mvn $MAVEN_CLI_OPTS spotless:check pmd:check test-compile -U
  allow_failure: false
  except:
    - master
    - tags

test:
  variables:
    JACOCO_REPORT_HTML: $CI_PROJECT_DIR/target/site/jacoco/index.html
  stage: test
  script:
    - *setup_alpine
    - *setup_git
    - mvn $MAVEN_CLI_OPTS verify -U
    - if [ -f $JACOCO_REPORT_HTML ]; then cat $JACOCO_REPORT_HTML | grep -o "Total[^%]*%"; fi
  allow_failure: false
  coverage: "/Total.*?([0-9]{1,3})%/"
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
  except:
    - master
    - tags

publish-snapshot-deb:
  image: debian:11-slim
  stage: publish-snapshot
  dependencies:
    - test
  script:
    - *setup_debian
    - *setup_git
    - PROJECT_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
    - echo $PROJECT_VERSION
    - rm -rvf **/*.example
    - cp -rv ${APPLICATION_PROPERTIES_SNAPSHOT_DEB} src/main/resources/application.properties
    - mvn $MAVEN_CLI_OPTS clean package -P deb -DskipTests
    - cd target && FILENAME_DEB=$(ls *.deb | head -n 1)
    - echo $FILENAME_DEB
    - lftp -c "set ftp:ssl-allow no; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST; mirror -Rv --file=$FILENAME_DEB --target-directory=./domains/download.pinodesk.com/public_html/snapshots/linux-deb/"
    - |
      curl -v --location 'https://api-staging.pinodesk.com/v1/releases' \
      --header 'Content-Type: application/json' \
      --header 'Authorization: Bearer '"$PINODESK_API_KEY_STAGING" \
      --data '{
          "name": "Pinodesk for Linux DEB v'"$PROJECT_VERSION"'",
          "platform": "linux-deb",
          "version": "'"$PROJECT_VERSION"'",
          "download_url": "https://download.pinodesk.com/snapshots/linux-deb/'"$FILENAME_DEB"'"
      }'
  allow_failure: false
  only:
    - develop
  when: manual

publish-snapshot-exe:
  image: busybox
  stage: publish-snapshot
  dependencies:
    - test
  script:
    - echo "Continue on Jenkins https://optiplex.pinodesk.com/jenkins/job/pinodesk-develop-build"
  allow_failure: false
  only:
    - develop
  when: manual

release:
  stage: release
  dependencies:
    - test
  script:
    - *setup_alpine
    - *setup_git
    - mvn $MAVEN_CLI_OPTS gitflow:release -DallowSnapshots -DversionDigitToIncrement=$RELEASE_DIGIT -DargLine=$MAVEN_CLI_OPTS
  only:
    - develop
  when: manual

publish-release-deb:
  image: debian:11-slim
  stage: publish-release
  dependencies:
    - release
  script:
    - *setup_debian
    - *setup_git
    - PROJECT_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
    - echo $PROJECT_VERSION
    - rm -rvf **/*.example
    - cp -rv ${APPLICATION_PROPERTIES_RELEASE_DEB} src/main/resources/application.properties
    - mvn $MAVEN_CLI_OPTS clean package -P deb -DskipTests
    - cd target && FILENAME_DEB=$(ls *.deb | head -n 1)
    - echo $FILENAME_DEB
    - lftp -c "set ftp:ssl-allow no; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST; mirror -Rv --file=$FILENAME_DEB --target-directory=./domains/download.pinodesk.com/public_html/releases/linux-deb/"
    - |
      curl -v --location 'https://api.pinodesk.com/v1/releases' \
      --header 'Content-Type: application/json' \
      --header 'Authorization: Bearer '"$PINODESK_API_KEY_PRODUCTION" \
      --data '{
          "name": "Pinodesk for Linux DEB v'"$PROJECT_VERSION"'",
          "platform": "linux-deb",
          "version": "'"$PROJECT_VERSION"'",
          "download_url": "https://download.pinodesk.com/releases/linux-deb/'"$FILENAME_DEB"'"
      }'
  allow_failure: false
  only:
    - master
  when: manual

publish-release-exe:
  image: busybox
  stage: publish-release
  dependencies:
    - test
  script:
    - echo "Continue on Jenkins https://optiplex.pinodesk.com/jenkins/job/pinodesk-master-build"
  allow_failure: false
  only:
    - master
  when: manual

hotfix-start:
  stage: release
  dependencies:
    - release
  script:
    - *setup_alpine
    - *setup_git
    - mvn $MAVEN_CLI_OPTS gitflow:hotfix-start -DhotfixVersionDigitToIncrement=$HOTFIX_DIGIT -DargLine=$MAVEN_CLI_OPTS
    - git push origin HEAD
  only:
    - master
  when: manual

# Inspired from here: https://github.com/viesure/blog-gitflow-maven/blob/master/.gitlab-ci.yml
hotfix-finish:
  stage: release
  dependencies:
    - hotfix-start
  script:
    - *setup_alpine
    - *setup_git
    # Manually fix the git refs. gitflow plugin uses the heads ref, but we do not have it set up locally, however we have the remote ref
    - git symbolic-ref refs/heads/$CI_COMMIT_BRANCH refs/remotes/origin/$CI_COMMIT_BRANCH
    - mvn $MAVEN_CLI_OPTS gitflow:hotfix-finish -DskipMergeDevBranch -DhotfixBranch=$CI_COMMIT_BRANCH -DargLine=$MAVEN_CLI_OPTS
  only:
    - /^hotfix\/.*$/
  when: manual
