<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>pinodesk</groupId>
    <artifactId>pinodesk</artifactId>
    <version>1.1.0-SNAPSHOT</version>
    <packaging>jar</packaging>
    <name>Pinodesk</name>
    <description>Pinodesk</description>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <project.mainClass>pinodesk.Main</project.mainClass>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <java.version>17</java.version>
        <dollar>$</dollar>
        <javapackager.version>1.7.5</javapackager.version>
    </properties>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework</groupId>
                <artifactId>spring-framework-bom</artifactId>
                <version>6.0.7</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.data</groupId>
                <artifactId>spring-data-bom</artifactId>
                <version>2021.2.10</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>com.konghq</groupId>
                <artifactId>unirest-java-bom</artifactId>
                <version>4.0.12</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <repositories>
        <repository>
            <id>mudiatech</id>
            <url>https://gitlab.com/api/v4/groups/64413151/-/packages/maven</url>
        </repository>
    </repositories>
    <dependencies>
        <!-- OpenJFX -->
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-controls</artifactId>
            <version>15.0.1</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-fxml</artifactId>
            <version>15.0.1</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-graphics</artifactId>
            <version>15.0.1</version>
        </dependency>
        <!-- Spring -->
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-jdbc</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-test</artifactId>
            <scope>test</scope>
        </dependency>
        <!-- Mudiatech -->
        <dependency>
            <groupId>com.mudiatech</groupId>
            <artifactId>sequel</artifactId>
            <version>0.1.0</version>
        </dependency>
        <dependency>
            <groupId>com.mudiatech</groupId>
            <artifactId>pandora</artifactId>
            <version>0.1.0</version>
        </dependency>
        <dependency>
            <groupId>com.mudiatech</groupId>
            <artifactId>toolbox</artifactId>
            <version>0.2.0</version>
        </dependency>
        <dependency>
            <groupId>com.mudiatech</groupId>
            <artifactId>norway</artifactId>
            <version>0.1.0</version>
        </dependency>
        <!-- Database -->
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <version>2.1.214</version>
        </dependency>
        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-core</artifactId>
            <version>9.16.3</version>
        </dependency>
        <!-- Test -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>5.9.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.testfx</groupId>
            <artifactId>testfx-junit5</artifactId>
            <version>4.0.16-alpha</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.testfx</groupId>
            <artifactId>openjfx-monocle</artifactId>
            <version>jdk-12.0.1+2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-inline</artifactId>
            <version>4.5.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-junit-jupiter</artifactId>
            <version>4.5.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.dbunit</groupId>
            <artifactId>dbunit</artifactId>
            <version>2.7.2</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>junit</groupId>
                    <artifactId>junit</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.github.springtestdbunit</groupId>
            <artifactId>spring-test-dbunit</artifactId>
            <version>1.3.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest-library</artifactId>
            <version>2.2</version>
            <scope>test</scope>
        </dependency>
        <!-- Other -->
        <dependency>
            <groupId>de.jensd</groupId>
            <artifactId>fontawesomefx-fontawesome</artifactId>
            <version>4.7.0-9.1.2</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.11</version>
        </dependency>
        <dependency>
            <groupId>commons-validator</groupId>
            <artifactId>commons-validator</artifactId>
            <version>1.7</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-dbcp2</artifactId>
            <version>2.9.0</version>
        </dependency>
        <dependency>
            <groupId>javax.annotation</groupId>
            <artifactId>javax.annotation-api</artifactId>
            <version>1.3.2</version>
        </dependency>
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
            <version>4.1.2</version>
        </dependency>
        <dependency>
            <groupId>xerces</groupId>
            <artifactId>xercesImpl</artifactId>
            <version>2.12.2</version>
        </dependency>
        <dependency>
            <groupId>org.aspectj</groupId>
            <artifactId>aspectjrt</artifactId>
            <version>1.9.9</version>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.aspectj</groupId>
            <artifactId>aspectjtools</artifactId>
            <version>1.9.9</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>2.0.7</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.4.8</version>
        </dependency>
        <dependency>
            <groupId>org.codehaus.janino</groupId>
            <artifactId>janino</artifactId>
            <version>3.0.6</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.11.2</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
            <version>2.11.2</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.24</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.jasypt</groupId>
            <artifactId>jasypt-spring4</artifactId>
            <version>1.9.3</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.konghq</groupId>
            <artifactId>unirest-java-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.konghq</groupId>
            <artifactId>unirest-objectmapper-jackson</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.sitture</groupId>
            <artifactId>unirest-curl</artifactId>
            <version>0.5.0</version>
        </dependency>
        <dependency>
            <groupId>com.github.oshi</groupId>
            <artifactId>oshi-core-java11</artifactId>
            <version>6.4.4</version>
        </dependency>
        <dependency>
            <groupId>javax.el</groupId>
            <artifactId>javax.el-api</artifactId>
            <version>3.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.glassfish</groupId>
            <artifactId>javax.el</artifactId>
            <version>3.0.0</version>
        </dependency>
    </dependencies>
    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
                <excludes>
                    <exclude>pinodesk/misc/*</exclude>
                </excludes>
            </resource>
        </resources>
        <plugins>
            <!--
            Resolve warning on the logs: `Using deprecated '-debug' fallback for parameter name resolution ...` 
            https://stackoverflow.com/questions/74845574/using-deprecated-debug-fallback-for-parameter-name-resolution-compile-the-af
            https://stackoverflow.com/questions/74600681/warning-printed-after-migrating-to-spring-boot-3-0-spring-integration-6-0/74601911#74601911
            -->
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>
                    <parameters>true</parameters>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>3.1.0</version>
                <configuration>
                    <encoding>${project.build.sourceEncoding}</encoding>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.22.0</version>
                <configuration>
                    <trimStackTrace>false</trimStackTrace>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.openjfx</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>0.0.4</version>
                <configuration>
                    <mainClass>${project.mainClass}</mainClass>
                    <includePathExceptionsInClasspath>true</includePathExceptionsInClasspath>
                    <options>
                        <option>--add-opens=javafx.graphics/javafx.scene=ALL-UNNAMED</option>
                        <option>--add-exports=javafx.graphics/com.sun.javafx.print=ALL-UNNAMED</option>
                    </options>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>0.8.8</version>
                <configuration>
                    <excludes>
                        <exclude>pinodesk/desktop/domain/*</exclude>
                        <exclude>pinodesk/desktop/constant/*</exclude>
                        <exclude>pinodesk/desktop/misc/*</exclude>
                        <exclude>pinodesk/desktop/viewmodel/*</exclude>
                    </excludes>
                </configuration>
                <executions>
                    <execution>
                        <id>default-prepare-agent</id>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>default-report</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>default-check</id>
                        <goals>
                            <goal>check</goal>
                        </goals>
                        <configuration>
                            <rules>
                                <rule>
                                    <element>BUNDLE</element>
                                    <limits>
                                        <limit>
                                            <counter>INSTRUCTION</counter>
                                            <value>COVEREDRATIO</value>
                                            <minimum>0.00</minimum>
                                        </limit>
                                    </limits>
                                </rule>
                            </rules>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>com.diffplug.spotless</groupId>
                <artifactId>spotless-maven-plugin</artifactId>
                <version>2.22.3</version>
                <configuration>
                    <java>
                        <removeUnusedImports />
                        <eclipse>
                            <file>${basedir}/default-formatter.xml</file>
                        </eclipse>
                    </java>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-pmd-plugin</artifactId>
                <version>3.16.0</version>
                <configuration>
                    <rulesets>
                        <ruleset>default-ruleset.xml</ruleset>
                    </rulesets>
                    <printFailingErrors>true</printFailingErrors>
                    <linkXRef>false</linkXRef>
                    <failurePriority>2</failurePriority>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>net.sourceforge.pmd</groupId>
                        <artifactId>pmd-core</artifactId>
                        <version>6.44.0</version>
                    </dependency>
                    <dependency>
                        <groupId>net.sourceforge.pmd</groupId>
                        <artifactId>pmd-java</artifactId>
                        <version>6.44.0</version>
                    </dependency>
                </dependencies>
            </plugin>
            <plugin>
                <groupId>com.amashchenko.maven.plugin</groupId>
                <artifactId>gitflow-maven-plugin</artifactId>
                <version>1.19.0</version>
                <configuration>
                    <mvnExecutable>./mvnw</mvnExecutable>
                    <skipTestProject>true</skipTestProject>
                </configuration>
            </plugin>
            <!--
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <version>3.1.0</version>
                <executions>
                    <execution>
                        <id>rename-profile-prefixed-files</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <target>
                                <copy
                                    file="${project.build.outputDirectory}/application-${currentProfile}.properties"
                                    tofile="${project.build.outputDirectory}/application.properties" />
                                <copy
                                    file="${project.build.outputDirectory}/logback-${currentProfile}.xml"
                                    tofile="${project.build.outputDirectory}/logback.xml" />
                                <delete>
                                    <fileset dir="${project.build.outputDirectory}">
                                        <include name="application-*.properties" />
                                        <include name="logback-*.xml" />
                                    </fileset>
                                </delete>
                            </target>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            -->
        </plugins>
    </build>
    <profiles>
        <profile>
            <id>dev</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <properties>
                <currentProfile>dev</currentProfile>
            </properties>
        </profile>
        <profile>
            <id>exe</id>
            <properties>
                <currentProfile>exe</currentProfile>
            </properties>
            <build>
                <plugins>
                    <plugin>
                        <groupId>io.github.fvarrui</groupId>
                        <artifactId>javapackager</artifactId>
                        <version>${javapackager.version}</version>
                        <executions>
                            <execution>
                                <phase>package</phase>
                                <goals>
                                    <goal>package</goal>
                                </goals>
                                <configuration>
                                    <name>${project.name}</name>
                                    <displayName>${project.name}</displayName>
                                    <organizationName>${project.name}</organizationName>
                                    <mainClass>${project.mainClass}</mainClass>
                                    <bundleJre>true</bundleJre>
                                    <!-- Required by apache poi, related issue
                                    https://github.com/traccar/traccar/issues/4126 -->
                                    <additionalModules>jdk.charsets</additionalModules>
                                    <platform>windows</platform>
                                    <winConfig>
                                        <generateMsi>false</generateMsi>
                                        <setupMode>installForAllUsers</setupMode>
                                        <fileDescription>${project.description}</fileDescription>
                                        <disableWelcomePage>false</disableWelcomePage>
                                        <disableDirPage>false</disableDirPage>
                                        <disableFinishedPage>false</disableFinishedPage>
                                        <disableRunAfterInstall>false</disableRunAfterInstall>
                                        <removeOldLibs>true</removeOldLibs>
                                        <setupLanguages>
                                            <english>compiler:Default.isl</english>
                                        </setupLanguages>
                                        <signing>
                                            <storetype>PKCS12</storetype>
                                            <keystore>
                                                src/main/resources/Mudiatech_Code_Signing_Certificate.p12</keystore>
                                            <storepass>Secret1234</storepass>
                                        </signing>
                                    </winConfig>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>deb</id>
            <properties>
                <currentProfile>deb</currentProfile>
            </properties>
            <build>
                <plugins>
                    <plugin>
                        <groupId>io.github.fvarrui</groupId>
                        <artifactId>javapackager</artifactId>
                        <version>${javapackager.version}</version>
                        <executions>
                            <execution>
                                <phase>package</phase>
                                <goals>
                                    <goal>package</goal>
                                </goals>
                                <configuration>
                                    <name>${project.name}</name>
                                    <displayName>${project.name}</displayName>
                                    <organizationName>${project.name}</organizationName>
                                    <mainClass>${project.mainClass}</mainClass>
                                    <bundleJre>true</bundleJre>
                                    <!-- Required by apache poi, related issue
                                    https://github.com/traccar/traccar/issues/4126 -->
                                    <additionalModules>jdk.charsets</additionalModules>
                                    <platform>linux</platform>
                                    <linuxConfig>
                                        <generateAppImage>false</generateAppImage>
                                        <generateRpm>false</generateRpm>
                                        <generateDeb>true</generateDeb>
                                    </linuxConfig>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>rpm</id>
            <properties>
                <currentProfile>rpm</currentProfile>
            </properties>
            <build>
                <plugins>
                    <plugin>
                        <groupId>io.github.fvarrui</groupId>
                        <artifactId>javapackager</artifactId>
                        <version>${javapackager.version}</version>
                        <executions>
                            <execution>
                                <phase>package</phase>
                                <goals>
                                    <goal>package</goal>
                                </goals>
                                <configuration>
                                    <name>${project.name}</name>
                                    <displayName>${project.name}</displayName>
                                    <organizationName>${project.name}</organizationName>
                                    <mainClass>${project.mainClass}</mainClass>
                                    <bundleJre>true</bundleJre>
                                    <!-- Required by apache poi, related issue
                                    https://github.com/traccar/traccar/issues/4126 -->
                                    <additionalModules>jdk.charsets</additionalModules>
                                    <platform>linux</platform>
                                    <linuxConfig>
                                        <generateAppImage>false</generateAppImage>
                                        <generateRpm>true</generateRpm>
                                        <generateDeb>false</generateDeb>
                                    </linuxConfig>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>pkg</id>
            <properties>
                <currentProfile>pkg</currentProfile>
            </properties>
            <build>
                <plugins>
                    <plugin>
                        <groupId>io.github.fvarrui</groupId>
                        <artifactId>javapackager</artifactId>
                        <version>${javapackager.version}</version>
                        <executions>
                            <execution>
                                <phase>package</phase>
                                <goals>
                                    <goal>package</goal>
                                </goals>
                                <configuration>
                                    <name>${project.name}</name>
                                    <displayName>${project.name}</displayName>
                                    <organizationName>${project.name}</organizationName>
                                    <mainClass>${project.mainClass}</mainClass>
                                    <bundleJre>true</bundleJre>
                                    <!-- Required by apache poi, related issue
                                    https://github.com/traccar/traccar/issues/4126 -->
                                    <additionalModules>jdk.charsets</additionalModules>
                                    <platform>mac</platform>
                                    <macConfig>
                                        <generateDmg>false</generateDmg>
                                        <generatePkg>true</generatePkg>
                                    </macConfig>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>