label.productNameOrCode=Nama atau kode produk
label.add=Tambah
label.new=Baru
label.saveAsDraft=Simpan Draf
label.openDraft=Buka Draf 
label.priceCheck=Cek Harga 
label.pay=Bayar
label.cancel=Batal 
label.discount=Diskon 
label.subtotal=Subtotal 
label.total=Total 
label.productCode=Kode Produk 
label.productName=Nama Produk 
label.quantity=Jumlah 
label.price=Harga 

lbl.menu.master=Master
lbl.menu.transaction=Transaksi
lbl.menu.settings=Pengaturan

btn.menu.products=Produk
btn.menu.customers=Pelanggan
btn.menu.suppliers=Pemasok
btn.menu.stockopname=Stock Opname
btn.menu.sales=Penjualan
btn.menu.purchases=Pembelian
btn.menu.payables=Hutang
btn.menu.receivables=Piutang
btn.menu.cashflow=Cash Flow
btn.menu.system=Sistem
btn.menu.users=Pengguna
btn.menu.usergroups=Kelompok Pengguna
btn.menu.languages=Bahasa

lbl.title.products=Produk

lbl.name=Nama
lbl.code=Kode
lbl.category=Kategori
lbl.quantity=Jumlah
lbl.unit=Satuan
lbl.price=Harga
lbl.purchaseprice=Harga Beli
lbl.sellingprice=Harga Jual
lbl.createdat=Dibuat Pada
lbl.updatedat=Diubah Pada

btn.clear=Kosongkan
btn.search=Cari
