label.productNameOrCode=Product name or code 
label.add=Add
label.new=New 
label.saveAsDraft=Save as Draft 
label.openDraft=Open Draft 
label.priceCheck=Price Check 
label.pay=Pay
label.cancel=Cancel 
label.discount=Discount 
label.subtotal=Subtotal 
label.total=Total 
label.productCode=Product Code 
label.productName=Product Name  
label.quantity=Quantity  
label.price=Price 

lbl.menu.master=Master
lbl.menu.transaction=Transaction
lbl.menu.settings=Settings

btn.menu.products=Products
btn.menu.customers=Customers
btn.menu.suppliers=Suppliers
btn.menu.stockopname=Stock Opname
btn.menu.sales=Sales
btn.menu.purchases=Purchases
btn.menu.payables=Payables
btn.menu.receivables=Receivables
btn.menu.cashflow=Cash Flow
btn.menu.configuration=Configuration
btn.menu.users=Users
btn.menu.usergroups=User Groups
btn.menu.languages=Languages

lbl.title.products=Products
lbl.title.editproduct=Edit Product
lbl.title.productcategories=Product Categories

lbl.name=Name
lbl.code=Code
lbl.barcode=Barcode
lbl.category=Category
lbl.description=Description
lbl.quantity=Quantity
lbl.unit=Unit
lbl.price=Price
lbl.purchaseprice=Purchase Price
lbl.sellingprice=Selling Price
lbl.sellingpriceperunit=Selling Price (Per Unit)
lbl.sellingpricebeforetax=Selling Price (Before Tax)
lbl.createdat=Created at
lbl.updatedat=Updated at
lbl.rows=Rows
lbl.expireddate=Expired Date
lbl.supplier=Supplier
lbl.profit=Profit
lbl.rack=Rack
lbl.drugcategory=Drug Category
lbl.prescriptionprice=Prescription Price
lbl.indication=Indication
lbl.contraindication=Contraindication
lbl.purchasequantity=Purchase Quantity

btn.clear=Clear
btn.search=Search
btn.add=Add
btn.cancel=Cancel
btn.save=Save

chk.includesvat=Includes VAT
chk.wholesale=Wholesale

message.loadingdata=Loading data
message.nodata=No data
