label.productNameOrCode=Nama atau kode produk
label.add=Tambah
label.new=Baru
label.saveAsDraft=Simpan Draf
label.openDraft=Buka Draf 
label.priceCheck=Cek Harga 
label.pay=Bayar
label.cancel=Batal 
label.discount=Diskon 
label.subtotal=Subtotal 
label.total=Total 
label.productCode=Kode Produk 
label.productName=Nama Produk 
label.quantity=Jumlah 
label.price=Harga 
