lbl.menu.master=Master
lbl.menu.transaction=Transaction
lbl.menu.settings=Settings

lbl.title.products=Products
lbl.title.editproduct=Edit Product
lbl.title.productcategories=Product Categories

lbl.name=Name
lbl.code=Code
lbl.barcode=Barcode
lbl.category=Category
lbl.description=Description
lbl.quantity=Quantity
lbl.unit=Unit
lbl.price=Price
lbl.purchaseprice=Purchase Price
lbl.sellingprice=Selling Price
lbl.sellingpriceperunit=Selling Price (Per Unit)
lbl.sellingpricebeforetax=Selling Price Before Tax
lbl.createdat=Created at
lbl.updatedat=Updated at
lbl.rows=Rows
lbl.expireddate=Expired Date
lbl.supplier=Supplier
lbl.profit=Profit
lbl.rack=Rack
lbl.drugcategory=Drug Category
lbl.prescriptionprice=Prescription Price
lbl.indication=Indication
lbl.contraindication=Contraindication
lbl.purchasequantity=Purchase Quantity
lbl.wholesale=Wholesale
lbl.drugspecific=Drug Specific
lbl.vat=VAT
lbl.information=Information
lbl.error=Error
lbl.loadingdata=Loading data
lbl.nodata=No data

btn.menu.products=Products
btn.menu.customers=Customers
btn.menu.suppliers=Suppliers
btn.menu.stockopname=Stock Opname
btn.menu.sales=Sales
btn.menu.purchases=Purchases
btn.menu.payables=Payables
btn.menu.receivables=Receivables
btn.menu.cashflow=Cash Flow
btn.menu.configuration=Configuration
btn.menu.users=Users
btn.menu.usergroups=User Groups
btn.menu.languages=Languages

btn.clear=Clear
btn.search=Search
btn.add=Add
btn.cancel=Cancel
btn.save=Save

chk.includesvat=Includes VAT

# Messages

SUCCESS_EDIT_PRODUCT=Successfully update product

ERROR_EMPTY_NAME=Name cannot be empty
ERROR_EMPTY_CODE=Code cannot be empty 
ERROR_EMPTY_CATEGORY=Category cannot be empty 
ERROR_EMPTY_PURCHASE_PRICE=Purchase Price cannot be empty 
ERROR_EMPTY_SELLING_PRICE=Selling Price cannot be empty 
ERROR_EMPTY_UNIT=Unit cannot be empty 
ERROR_EMPTY_DRUG_CATEGORY=Drug category cannot be empty 
