lbl.menu.master=Master
lbl.menu.transaction=Transaksi
lbl.menu.settings=Pengaturan

lbl.title.products=Produk
lbl.title.editproduct=Ubah Produk
lbl.title.productcategories=Kategori Produk

lbl.name=Nama
lbl.code=Kode
lbl.barcode=Barcode
lbl.category=Kategori
lbl.description=Deskripsi
lbl.quantity=Jumlah
lbl.unit=Satuan
lbl.price=Harga
lbl.purchaseprice=Harga Beli
lbl.sellingprice=Harga Jual
lbl.sellingpriceperunit=Harga Jual (Per Satuan)
lbl.sellingpricebeforetax=Harga Jual Sebelum Pajak
lbl.createdat=Dibuat Pada
lbl.updatedat=Diubah Pada
lbl.rows=Baris
lbl.expireddate=Tanggal Kadaluarsa
lbl.supplier=Pemasok
lbl.profit=Laba
lbl.rack=Rak
lbl.drugcategory=Kategori Obat
lbl.prescriptionprice=Harga Resep
lbl.indication=Indikasi
lbl.contraindication=Kontraindikasi
lbl.purchasequantity=Jumlah Beli
lbl.wholesale=Grosir
lbl.drugspecific=Khusus Obat
lbl.vat=PPN
lbl.information=Informasi
lbl.error=Kesalahan
lbl.loadingdata=Memuat data
lbl.nodata=Tidak ada data

btn.menu.products=Produk
btn.menu.customers=Pelanggan
btn.menu.suppliers=Pemasok
btn.menu.stockopname=Stock Opname
btn.menu.sales=Penjualan
btn.menu.purchases=Pembelian
btn.menu.payables=Hutang
btn.menu.receivables=Piutang
btn.menu.cashflow=Cash Flow
btn.menu.configuration=Konfigurasi
btn.menu.users=Pengguna
btn.menu.usergroups=Kelompok Pengguna
btn.menu.languages=Bahasa

btn.clear=Kosongkan
btn.search=Cari
btn.add=Tambah
btn.cancel=Batal
btn.save=Simpan

chk.includesvat=Termasuk PPN

# Messages

SUCCESS_EDIT_PRODUCT=Berhasil mengubah produk

ERROR_EMPTY_NAME=Nama tidak boleh kosong 
ERROR_EMPTY_CODE=Kode tidak boleh kosong 
ERROR_EMPTY_CATEGORY=Kategori tidak boleh kosong 
ERROR_EMPTY_PURCHASE_PRICE=Harga Beli tidak boleh kosong
ERROR_EMPTY_SELLING_PRICE=Harga Jual tidak boleh kosong 
ERROR_EMPTY_UNIT=Satuan tidak boleh kosong 
ERROR_EMPTY_DRUG_CATEGORY=Kategori Obat tidak boleh kosong 
ERROR_INCORRECT_PRODUCT_CATEGORY_DRUGS=Kategori produk obat harus 'Obat-obatan'
