package pinus.desktop.constant;

public interface CacheNameConstants {
    String CONFIGURATION_MAP = "CONFIGURATION_MAP";
    String CONFIGURATION_BY_CODE = "CONFIGURATION_BY_CODE";
    String PRODUCTS_BY_FILTER = "PRODUCTS_BY_FILTER";
    String PRODUCTS_BY_KEYWORD = "PRODUCTS_BY_KEYWORD";
    String PRODUCT_CATEGORIES_BY_KEYWORD = "PRODUCT_CATEGORIES_BY_KEYWORD";
    String RACKS_ALL = "RACKS_ALL";
    String RACKS_BY_KEYWORD = "RACKS_BY_KEYWORD";
    String UNITS_ALL = "UNITS_ALL";
    String UNITS_BY_KEYWORD = "UNITS_BY_KEYWORD";
    String DRUG_CATEGORY_BASES_ALL = "DRUG_CATEGORY_BASES_ALL";
    String DRUG_CATEGORIES_BY_KEYWORD = "DRUG_CATEGORIES_BY_KEYWORD";
    String CUSTOMERS_BY_FILTER = "CUSTOMERS_BY_FILTER";
    String CUSTOMERS_BY_KEYWORD = "CUSTOMERS_BY_KEYWORD";
    String SUPPLIERS_BY_FILTER = "SUPPLIERS_BY_FILTER";
    String SUPPLIERS_BY_KEYWORD = "SUPPLIERS_BY_KEYWORD";
    String LANGUAGES_ALL = "LANGUAGES_ALL";
    String PURCHASES_BY_FILTER = "PURCHASES_BY_FILTER";
    String SALES_BY_FILTER = "SALES_BY_FILTER";
    String DOCTORS_BY_KEYWORD = "DOCTORS_BY_KEYWORD";
    String DOCTORS_BY_FILTER = "DOCTORS_BY_FILTER";
    String DOCTOR_CATEGORIES_BY_KEYWORD = "DOCTOR_CATEGORIES_BY_KEYWORD";
    String PAYABLES_BY_FILTER = "PAYABLES_BY_FILTER";
}
