package pinus.desktop.constant;

/**
 * Errors related with domain at repository or service level. The code for this
 * error should follow this format: "DE" + domain category number (01-99) +
 * error number (001-999).
 */
public enum DomainError {

    // Product (01)
    PRODUCT_NOT_FOUND_BY_ID("DE01001", MessageCode.ERROR_PRODUCT_NOT_FOUND_BY_ID),
    PRODUCT_EXISTS_BY_CODE("DE01002", MessageCode.ERROR_PRODUCT_EXISTS_BY_CODE),
    PRODUCT_EXISTS_BY_BARCODE("DE01003", MessageCode.ERROR_PRODUCT_EXISTS_BY_BARCODE),
    PRODUCT_OTHER_EXISTS_BY_CODE("DE01004", MessageCode.ERROR_PRODUCT_EXISTS_BY_CODE),
    PRODUCT_OTHER_EXISTS_BY_BARCODE("DE01005", MessageCode.ERROR_PRODUCT_EXISTS_BY_BARCODE),
    PRODUCT_OTHER_EXISTS_BY_NAME_AND_UNIT("DE01006", MessageCode.ERROR_PRODUCT_EXISTS_BY_NAME_AND_UNIT),
    PRODUCT_EXISTS_BY_NAME_AND_UNIT("DE01007", MessageCode.ERROR_PRODUCT_EXISTS_BY_NAME_AND_UNIT),
    PRODUCT_EXPIRY_QUANTITY_EXCEEDS_PRODUCT_STOCK("DE01008", MessageCode.ERROR_INCORRECT_PRODUCT_EXPIRY_QUANTITY),

    // Product category (02)
    PRODUCT_CATEGORY_NOT_FOUND_BY_ID("DE02001", MessageCode.ERROR_PRODUCT_CATEGORY_NOT_FOUND_BY_ID),

    // Unit (03)
    UNIT_NOT_FOUND_BY_ID("DE03001", MessageCode.ERROR_UNIT_NOT_FOUND_BY_ID),

    // Rack (04)
    RACK_NOT_FOUND_BY_ID("DE04001", MessageCode.ERROR_RACK_NOT_FOUND_BY_ID),

    // Drug category (05)
    DRUG_CATEGORY_NOT_FOUND_BY_ID("DE05001", MessageCode.ERROR_DRUG_CATEGORY_NOT_FOUND_BY_ID),

    // Contact (06)
    CUSTOMER_NOT_FOUND_BY_ID("DE06001", MessageCode.ERROR_CUSTOMER_NOT_FOUND_BY_ID),
    CUSTOMER_EXISTS_BY_CODE("DE06002", MessageCode.ERROR_CUSTOMER_EXISTS_BY_CODE),
    CUSTOMER_EXISTS_BY_EMAIL("DE06003", MessageCode.ERROR_CUSTOMER_EXISTS_BY_EMAIL),
    CUSTOMER_EXISTS_BY_PHONE("DE06004", MessageCode.ERROR_CUSTOMER_EXISTS_BY_PHONE),
    CUSTOMER_OTHER_EXISTS_BY_CODE("DE06005", MessageCode.ERROR_CUSTOMER_EXISTS_BY_CODE),
    CUSTOMER_OTHER_EXISTS_BY_EMAIL("DE06006", MessageCode.ERROR_CUSTOMER_EXISTS_BY_EMAIL),
    CUSTOMER_OTHER_EXISTS_BY_PHONE("DE06007", MessageCode.ERROR_CUSTOMER_EXISTS_BY_PHONE),

    // Supplier (07)
    SUPPLIER_NOT_FOUND_BY_ID("DE07001", MessageCode.ERROR_SUPPLIER_NOT_FOUND_BY_ID),
    SUPPLIER_EXISTS_BY_CODE("DE07002", MessageCode.ERROR_SUPPLIER_EXISTS_BY_CODE),
    SUPPLIER_EXISTS_BY_EMAIL("DE76003", MessageCode.ERROR_SUPPLIER_EXISTS_BY_EMAIL),
    SUPPLIER_EXISTS_BY_PHONE("DE07004", MessageCode.ERROR_SUPPLIER_EXISTS_BY_PHONE),
    SUPPLIER_OTHER_EXISTS_BY_CODE("DE07005", MessageCode.ERROR_SUPPLIER_EXISTS_BY_CODE),
    SUPPLIER_OTHER_EXISTS_BY_EMAIL("DE07006", MessageCode.ERROR_SUPPLIER_EXISTS_BY_EMAIL),
    SUPPLIER_OTHER_EXISTS_BY_PHONE("DE07007", MessageCode.ERROR_SUPPLIER_EXISTS_BY_PHONE),

    // Supplier contact (08)
    SUPPLIER_CONTACT_EXISTS_BY_EMAIL("DE08001", MessageCode.ERROR_SUPPLIER_CONTACT_EXISTS_BY_EMAIL),
    SUPPLIER_CONTACT_EXISTS_BY_PHONE("DE08002", MessageCode.ERROR_SUPPLIER_CONTACT_EXISTS_BY_PHONE),

    // Purchase (09)
    PURCHASE_EXISTS_BY_INVOICE_NUMBER_AND_SUPPLIER_ID("DE09001",
            MessageCode.ERROR_PURCHASE_EXISTS_BY_INVOICE_NUMBER_AND_SUPPLIER_ID),
    PURCHASE_OTHER_EXISTS_BY_INVOICE_NUMBER_AND_SUPPLIER_ID("DE09002",
            MessageCode.ERROR_PURCHASE_EXISTS_BY_INVOICE_NUMBER_AND_SUPPLIER_ID),
    PURCHASE_NOT_FOUND_BY_ID("DE09003", MessageCode.ERROR_PURCHASE_NOT_FOUND_BY_ID),

    // Sale (10)
    SALE_EXISTS_BY_INVOICE_NUMBER("DE10001", MessageCode.ERROR_SALE_EXISTS_BY_INVOICE_NUMBER),
    PRODUCT_QUANTITY_INSUFFICIENT_FOR_SALE("DE10002", MessageCode.ERROR_PRODUCT_QUANTITY_INSUFFICIENT_FOR_SALE),
    SALE_NOT_FOUND_BY_ID("DE10003", MessageCode.ERROR_SALE_NOT_FOUND_BY_ID),
    SALE_OTHER_EXISTS_BY_INVOICE_NUMBER("DE10004", MessageCode.ERROR_SALE_EXISTS_BY_INVOICE_NUMBER),

    // Doctor (11)
    DOCTOR_EXISTS_BY_CODE("DE11001", MessageCode.ERROR_DOCTOR_EXISTS_BY_CODE),
    DOCTOR_EXISTS_BY_REGISTRATION_NUMBER("DE11002", MessageCode.ERROR_DOCTOR_EXISTS_BY_REGISTRATION_NUMBER),
    DOCTOR_EXISTS_BY_MEDICAL_LICENSE_NUMBER("DE11003", MessageCode.ERROR_DOCTOR_EXISTS_BY_MEDICAL_LICENSE_NUMBER),;

    private final String code;
    private final MessageCode messageCode;

    private DomainError(String code, MessageCode messageCode) {
        this.code = code;
        this.messageCode = messageCode;
    }

    public String code() {
        return this.code;
    }

    public MessageCode messageCode() {
        return this.messageCode;
    }

}
