lbl.menu.master=Master
lbl.menu.transaction=Transaksi
lbl.menu.settings=Pengaturan

lbl.title.products=Produk
lbl.title.editproduct=Ubah Produk
lbl.title.filterproduct=Filter Produk
lbl.title.addproduct=Tambah Produk
lbl.title.contacts=Kontak
lbl.title.filtercontact=Filter Kontak
lbl.title.addcontact=Tambah Kontak
lbl.title.customers=Pelanggan
lbl.title.filtercustomer=Filter Pelanggan
lbl.title.addcustomer=Tambah Pelanggan
lbl.title.editcustomer=Ubah Pelanggan

lbl.name=Nama
lbl.code=Kode
lbl.barcode=Barcode
lbl.category=Kategori
lbl.description=Deskripsi
lbl.quantity=Jumlah
lbl.unit=Satuan
lbl.price=Harga
lbl.purchaseprice=Harga Beli
lbl.sellingprice=Harga Jual
lbl.sellingpriceperunit=Harga Jual (Per Satuan)
lbl.sellingpricebeforetax=Harga Jual Sebelum Pajak
lbl.createdat=Dibuat Pada
lbl.updatedat=Diubah Pada
lbl.rows=Baris
lbl.expireddate=Tanggal Kadaluarsa
lbl.supplier=Pemasok
lbl.profit=Laba
lbl.rack=Rak
lbl.drugcategory=Kategori Obat
lbl.prescriptionprice=Harga Resep
lbl.indication=Indikasi
lbl.contraindication=Kontraindikasi
lbl.purchasequantity=Jumlah Beli
lbl.wholesale=Grosir
lbl.drugspecific=Khusus Obat
lbl.vat=PPN
lbl.information=Informasi
lbl.error=Kesalahan
lbl.loadingdata=Memuat data
lbl.nodata=Tidak ada data
lbl.includesvat=Termasuk PPN
lbl.quantitymin=Jumlah Min.
lbl.quantitymax=Jumlah Maks.
lbl.purchasepricemin=Harga Beli Min.
lbl.purchasepricemax=Harga Beli Maks.
lbl.sellingpricemin=Harga Jual Min.
lbl.sellingpricemax=Harga Jual Maks.
lbl.expireddatemin=Tanggal Kadaluarsa Min.
lbl.expireddatemax=Tanggal Kadaluarsa Maks.
lbl.yes=Ya
lbl.no=Tidak
lbl.systemerror=Kesalahan Sistem
lbl.details=Rincian
lbl.confirmation=Konfirmasi
lbl.phone=Telepon
lbl.email=Email
lbl.address=Alamat
lbl.companyname=Nama Perusahaan
lbl.all=Semua
lbl.customer=Pelanggan
lbl.supplier=Pemasok
lbl.contacttype=Tipe Kontak

btn.menu.products=Produk
btn.menu.suppliers=Pemasok
btn.menu.customers=Pelanggan
btn.menu.stockopname=Stock Opname
btn.menu.sales=Penjualan
btn.menu.purchases=Pembelian
btn.menu.payables=Hutang
btn.menu.receivables=Piutang
btn.menu.cashflow=Cash Flow
btn.menu.configuration=Konfigurasi
btn.menu.users=Pengguna
btn.menu.usergroups=Kelompok Pengguna
btn.menu.languages=Bahasa

btn.yes=Ya
btn.no=Tidak
btn.ok=Oke
btn.clear=Kosongkan
btn.search=Cari
btn.add=Tambah
btn.cancel=Batal
btn.save=Simpan
btn.filter=Filter
btn.reset=Reset
btn.remove=Hapus
btn.saveandcopy=Simpan & Tambah (Salin)
btn.saveandadd=Simpan & Tambah

chk.includesvat=Termasuk PPN

# Messages

SUCCESS_ADD_PRODUCT=Berhasil menambahkan produk
SUCCESS_EDIT_PRODUCT=Berhasil mengubah produk
SUCCESS_REMOVE_PRODUCT=Berhasil menghapus produk
SUCCESS_REMOVE_SELECTED_PRODUCTS=Berhasil menghapus produk terpilih
SUCCESS_ADD_CONTACT=Berhasil menambahkan kontak
SUCCESS_REMOVE_CONTACT=Berhasil menghapus kontak
SUCCESS_REMOVE_SELECTED_CONTACTS=Berhasil menghapus kontak terpilih

ERROR_EMPTY_NAME=Nama tidak boleh kosong 
ERROR_EMPTY_CODE=Kode tidak boleh kosong 
ERROR_EMPTY_CATEGORY=Kategori tidak boleh kosong 
ERROR_EMPTY_PURCHASE_PRICE=Harga Beli tidak boleh kosong
ERROR_EMPTY_SELLING_PRICE=Harga Jual tidak boleh kosong 
ERROR_EMPTY_UNIT=Satuan tidak boleh kosong 
ERROR_EMPTY_DRUG_CATEGORY=Kategori Obat tidak boleh kosong 
ERROR_INCORRECT_PRODUCT_CATEGORY_DRUGS=Kategori produk obat harus 'Obat-obatan'
ERROR_EMPTY_CONTACT_TYPE=Tipe kontak tidak boleh kosong
ERROR_INVALID_EMAIL_FORMAT=Format email tidak valid
ERROR_INVALID_CODE_FORMAT=Format kode tidak valid

CONFIRMATION_REMOVE_PRODUCT=Produk ini akan dihapus, apakah Anda ingin melanjutkan?
CONFIRMATION_REMOVE_SELECTED_PRODUCTS=Produk terpilih akan dihapus, apakah Anda ingin melanjutkan?
CONFIRMATION_REMOVE_CONTACT=Kontak ini akan dihapus, apakah Anda ingin melanjutkan?
CONFIRMATION_REMOVE_SELECTED_CONTACTS=Kontak terpilih akan dihapus, apakah Anda ingin melanjutkan?

# Product
ERROR_PRODUCT_NOT_FOUND_BY_ID=Produk dengan ID tersebut tidak ditemukan
ERROR_PRODUCT_EXISTS_BY_CODE=Produk sudah ada dengan kode tersebut
ERROR_PRODUCT_EXISTS_BY_BARCODE=Produk sudah ada dengan barcode tersebut
ERROR_PRODUCT_EXISTS_BY_NAME_AND_UNIT=Produk sudah ada dengan nama dan satuan tersebut

# Drug category
ERROR_DRUG_CATEGORY_NOT_FOUND_BY_ID=Kategori obat dengan ID tersebt tidak ditemukan

# Product category
ERROR_PRODUCT_CATEGORY_NOT_FOUND_BY_ID=Kategori produk dengan ID tersebut tidak ditemukan

# Unit
ERROR_UNIT_NOT_FOUND_BY_ID=Satuan dengan ID tersebut tidak ditemukan

# Rack
ERROR_RACK_NOT_FOUND_BY_ID=Rak dengan ID tersebut tidak ditemukan

# Contact
CONTACT_NOT_FOUND_BY_ID=Kontak dengan ID tersebut tidak ditemukan
ERROR_CONTACT_EXISTS_BY_CODE_AND_TYPE=Kontak sudah ada dengan kode dan tipe kontak tersebut
