package toscabox.desktop.constant;

import com.gitlab.muhammadkholidb.pandora.utility.IMessage;

public enum MessageCode implements IMessage {
    
    ERROR_INCOMPLETE_FORM,
    ERROR_REQUIRED,
    ERROR_EMPTY_OR_BLANK,
    ERROR_EMPTY_NAME,
    ERROR_EMPTY_CODE,
    ERROR_EMPTY_CATEGORY,
    ERROR_EMPTY_PURCHASE_PRICE,
    ERROR_EMPTY_SELLING_PRICE,
    ERROR_EMPTY_UNIT,
    ERROR_EMPTY_DRUG_CATEGORY,
    ERROR_INCORRECT_PRODUCT_CATEGORY_DRUGS,
    ERROR_EMPTY_CONTACT_TYPE,
    ERROR_INVALID_EMAIL_FORMAT,
    ERROR_INVALID_CODE_FORMAT,
    ERROR_INVALID_DOMAIN_FORMAT,

    // Configuration
    SUCCESS_EDIT_CONFIGURATION,

    // Product
    SUCCESS_ADD_PRODUCT,
    SUCCESS_EDIT_PRODUCT,
    SUCCESS_REMOVE_PRODUCT,
    SUCCESS_REMOVE_SELECTED_PRODUCTS,
    CONFIRMATION_REMOVE_PRODUCT,
    CONFIRMATION_REMOVE_SELECTED_PRODUCTS,
    ERROR_PRODUCT_NOT_FOUND_BY_ID,
    ERROR_PRODUCT_EXISTS_BY_CODE,
    ERROR_PRODUCT_EXISTS_BY_BARCODE,
    ERROR_PRODUCT_EXISTS_BY_NAME_AND_UNIT,
    
    // Drug category
    ERROR_DRUG_CATEGORY_NOT_FOUND_BY_ID,

    // Product category
    ERROR_PRODUCT_CATEGORY_NOT_FOUND_BY_ID,

    // Unit
    ERROR_UNIT_NOT_FOUND_BY_ID,

    // Rack
    ERROR_RACK_NOT_FOUND_BY_ID,

    // Customer
    SUCCESS_ADD_CUSTOMER,
    SUCCESS_EDIT_CUSTOMER,
    SUCCESS_REMOVE_CUSTOMER,
    SUCCESS_REMOVE_SELECTED_CUSTOMERS,
    CONFIRMATION_REMOVE_CUSTOMER,
    CONFIRMATION_REMOVE_SELECTED_CUSTOMERS,
    ERROR_CUSTOMER_NOT_FOUND_BY_ID,
    ERROR_CUSTOMER_EXISTS_BY_CODE,
    ERROR_CUSTOMER_EXISTS_BY_EMAIL,
    ERROR_CUSTOMER_EXISTS_BY_PHONE,
    
    // Supplier
    SUCCESS_ADD_SUPPLIER,
    SUCCESS_ADD_SUPPLIER_CONTACT,
    SUCCESS_EDIT_SUPPLIER,
    SUCCESS_REMOVE_SUPPLIER,
    SUCCESS_REMOVE_SELECTED_SUPPLIERS,
    CONFIRMATION_REMOVE_SUPPLIER,
    CONFIRMATION_REMOVE_SELECTED_SUPPLIERS,
    ERROR_SUPPLIER_NOT_FOUND_BY_ID,
    ERROR_SUPPLIER_EXISTS_BY_CODE,
    ERROR_SUPPLIER_EXISTS_BY_EMAIL,
    ERROR_SUPPLIER_EXISTS_BY_PHONE, 
    
    // Supplier contact
    ERROR_SUPPLIER_CONTACT_EXISTS_BY_EMAIL,
    ERROR_SUPPLIER_CONTACT_EXISTS_BY_PHONE, 
    
    // Purchase
    SUCCESS_ADD_PURCHASE,
    ERROR_ORDER_DATE_GREATER_THAN_TODAY,

}
