package pinodesk.constant;

import com.mudiatech.pandora.utility.IMessage;

public enum MessageCode implements IMessage {

    ERROR_INCOMPLETE_FORM,
    ERROR_REQUIRED,
    ERROR_EMPTY_OR_BLANK,
    ERROR_EMPTY_NAME,
    ERROR_EMPTY_CODE,
    ERROR_EMPTY_CATEGORY,
    ERROR_EMPTY_PURCHASE_PRICE,
    ERROR_EMPTY_UNIT,
    ERROR_EMPTY_DRUG_CATEGORY,
    ERROR_INCORRECT_PRODUCT_CATEGORY_DRUGS,
    ERROR_EMPTY_CONTACT_TYPE,
    ERROR_INVALID_EMAIL_FORMAT,
    ERROR_INVALID_CODE_FORMAT,
    ERROR_INVALID_DOMAIN_FORMAT,
    ERROR_INVALID_DATE_FORMAT,
    ERROR_INCORRECT_PRODUCT_EXPIRY_QUANTITY,
    ERROR_INVALID_QUANTITY,
    ERROR_INVALID_BUYING_PRICE,
    ERROR_INVALID_GENERAL_SELLING_PRICE,
    ERROR_INVALID_PRESCRIPTION_SELLING_PRICE,
    ERROR_INVALID_EXPIRED_DATE,
    ERROR_INVALID_INVOICE_DATE,
    ERROR_INVALID_INVOICE_NUMBER,
    ERROR_INVALID_DUE_DATE,
    ERROR_EMPTY_PRODUCT,
    ERROR_EMPTY_SUPPLIER,
    ERROR_INVOICE_DATE_AFTER_TODAY,
    ERROR_DUE_DATE_BEFORE_TODAY,
    ERROR_EMPTY_PHONE_OR_EMAIL,
    ERROR_EMPTY_CURRENT_QUANTITY,
    ERROR_EMPTY_SELLING_PRICE,
    ERROR_EMPTY_QUANTITY,
    ERROR_EMPTY_FILE,
    ERROR_EMPTY_FULL_NAME,
    ERROR_EMPTY_USERNAME,
    ERROR_EMPTY_PASSWORD,
    ERROR_EMPTY_PASSWORD_CONFIRMATION,
    ERROR_MISMATCH_PASSWORD_CONFIRMATION,
    ERROR_EMPTY_USER_GROUP,
    ERROR_EMPTY_STORE_NAME,
    ERROR_PRINTER_NOT_FOUND,
    ERROR_PRINTER_UNAVAILABLE,
    ERROR_EMPTY_ACTIVATION_CODE,

    // Configuration
    SUCCESS_EDIT_CONFIGURATION_WITH_LOGOUT,
    SUCCESS_EDIT_CONFIGURATION,
    SUCCESS_BACKUP,
    SUCCESS_RESTORE,
    ERROR_DIFFERENT_BACKUP_APP_VERSION,
    SUCCESS_ACTIVATION,
    RESTORE_DATABASE_ERROR,
    BACKUP_DATABASE_ERROR,
    CONFIRMATION_RESTORE_DATA,
    CONFIRMATION_ACTIVATE_LATER,

    // Product
    SUCCESS_ADD_PRODUCT,
    SUCCESS_EDIT_PRODUCT,
    SUCCESS_REMOVE_PRODUCT,
    SUCCESS_REMOVE_SELECTED_PRODUCTS,
    SUCCESS_DOWNLOAD_TEMPLATE,
    SUCCESS_EXPORT_PRODUCTS,
    CONFIRMATION_REMOVE_PRODUCT,
    CONFIRMATION_REMOVE_SELECTED_PRODUCTS,
    ERROR_PRODUCT_NOT_FOUND_BY_ID,
    ERROR_PRODUCT_EXISTS_BY_CODE,
    ERROR_PRODUCT_EXISTS_BY_BARCODE,
    ERROR_PRODUCT_EXISTS_BY_NAME_AND_UNIT,
    ERROR_PRODUCT_CATEGORY_CUSTOM_PACKAGE_NOT_ALLOWED,
    ERROR_INSUFFICIENT_PACKAGE_QUANTITY,

    // Drug category
    ERROR_DRUG_CATEGORY_NOT_FOUND_BY_CODE,

    // Product category
    ERROR_PRODUCT_CATEGORY_NOT_FOUND_BY_ID,
    ERROR_PRODUCT_CATEGORY_NOT_FOUND_BY_CODE,

    // Unit
    ERROR_UNIT_NOT_FOUND_BY_ID,
    ERROR_UNIT_NOT_FOUND_BY_CODE,

    // Rack
    ERROR_RACK_NOT_FOUND_BY_ID,

    // Customer
    SUCCESS_ADD_CUSTOMER,
    SUCCESS_EDIT_CUSTOMER,
    SUCCESS_REMOVE_CUSTOMER,
    SUCCESS_REMOVE_SELECTED_CUSTOMERS,
    CONFIRMATION_REMOVE_CUSTOMER,
    CONFIRMATION_REMOVE_SELECTED_CUSTOMERS,
    ERROR_CUSTOMER_NOT_FOUND_BY_ID,
    ERROR_CUSTOMER_EXISTS_BY_CODE,
    ERROR_CUSTOMER_EXISTS_BY_EMAIL,
    ERROR_CUSTOMER_EXISTS_BY_PHONE,

    // Supplier
    SUCCESS_ADD_SUPPLIER,
    SUCCESS_ADD_SUPPLIER_CONTACT,
    SUCCESS_EDIT_SUPPLIER,
    SUCCESS_REMOVE_SUPPLIER,
    SUCCESS_REMOVE_SELECTED_SUPPLIERS,
    CONFIRMATION_REMOVE_SUPPLIER,
    CONFIRMATION_REMOVE_SELECTED_SUPPLIERS,
    ERROR_SUPPLIER_NOT_FOUND_BY_ID,
    ERROR_SUPPLIER_EXISTS_BY_CODE,
    ERROR_SUPPLIER_EXISTS_BY_EMAIL,
    ERROR_SUPPLIER_EXISTS_BY_PHONE,

    // Supplier contact
    ERROR_SUPPLIER_CONTACT_EXISTS_BY_EMAIL,
    ERROR_SUPPLIER_CONTACT_EXISTS_BY_PHONE,

    // Purchase
    SUCCESS_ADD_PURCHASE,
    SUCCESS_EDIT_PURCHASE,
    SUCCESS_REMOVE_PURCHASE,
    SUCCESS_REMOVE_SELECTED_PURCHASES,
    ERROR_PURCHASE_ORDER_DATE_GREATER_THAN_TODAY,
    ERROR_PURCHASE_EXISTS_BY_INVOICE_NUMBER_AND_SUPPLIER_ID,
    ERROR_PURCHASE_NOT_FOUND_BY_ID,
    ERROR_DISCOUNT_AMOUNT_PERCENTAGE_OUT_OF_RANGE,
    ERROR_DISCOUNT_AMOUNT_FIXED_AMOUNT_GREATER_THAN_BUYING_PRICE,
    ERROR_PAYABLE_PAYMENT_EXISTS_BY_SALE_ID,
    ERROR_PAYABLE_ALREADY_COMPLETED_BY_SALE_ID,
    CONFIRMATION_REMOVE_PURCHASE,
    CONFIRMATION_REMOVE_SELECTED_PURCHASES,
    CONFIRMATION_EDIT_PURCHASE,

    // Sale
    SUCCESS_ADD_SALE,
    SUCCESS_EDIT_SALE,
    SUCCESS_REMOVE_SALE,
    SUCCESS_REMOVE_SELECTED_SALES,
    CONFIRMATION_REMOVE_SALE,
    CONFIRMATION_REMOVE_SELECTED_SALES,
    CONFIRMATION_EDIT_SALE,
    ERROR_SALE_EXISTS_BY_INVOICE_NUMBER,
    ERROR_PRODUCT_QUANTITY_INSUFFICIENT_FOR_SALE,
    ERROR_SALE_QUANTITY_GREATER_THAN_PRODUCT_QUANTITY,
    ERROR_SALE_NOT_FOUND_BY_ID,
    ERROR_UNPAID_PAYMENT_WITH_EMPTY_CUSTOMER,
    ERROR_RECEIVABLE_PAYMENT_EXISTS_BY_SALE_ID,
    ERROR_RECEIVABLE_ALREADY_COMPLETED_BY_SALE_ID,
    ERROR_PAYMENT_AMOUNT_LOWER_THAN_SALE_AMOUNT,

    // Doctor
    SUCCESS_ADD_DOCTOR,
    SUCCESS_REMOVE_DOCTOR,
    SUCCESS_REMOVE_SELECTED_DOCTORS,
    CONFIRMATION_REMOVE_DOCTOR,
    CONFIRMATION_REMOVE_SELECTED_DOCTORS,
    ERROR_DOCTOR_NOT_FOUND_BY_ID,
    ERROR_DOCTOR_EXISTS_BY_CODE,
    ERROR_DOCTOR_EXISTS_BY_REGISTRATION_NUMBER,
    ERROR_DOCTOR_EXISTS_BY_MEDICAL_LICENSE_NUMBER,
    ERROR_DOCTOR_CATEGORY_NOT_FOUND_BY_ID,
    ERROR_DOCTOR_EXISTS_BY_EMAIL,
    ERROR_DOCTOR_EXISTS_BY_PHONE,

    // Drug classification
    ERROR_DRUG_CLASSIFICATION_NOT_FOUND_BY_ID,
    ERROR_DRUG_CLASSIFICATION_NOT_FOUND_BY_CODE,

    // User group
    SUCCESS_ADD_USER_GROUP,
    SUCCESS_EDIT_USER_GROUP,
    SUCCESS_REMOVE_USER_GROUP,
    SUCCESS_REMOVE_SELECTED_USER_GROUPS,
    CONFIRMATION_REMOVE_USER_GROUP,
    CONFIRMATION_REMOVE_SELECTED_USER_GROUPS,
    ERROR_USER_GROUP_ADMINISTRATOR_MODIFICATION_FORBIDDEN,
    ERROR_USER_GROUP_ADMINISTRATOR_MUST_HAVE_USER,
    ERROR_USER_GROUP_NOT_FOUND_BY_ID,
    ERROR_USER_GROUP_EXISTS_BY_NAME,
    ERROR_DELETE_USER_GROUP_USER_EXISTS,

    // User
    SUCCESS_ADD_USER,
    SUCCESS_EDIT_USER,
    SUCCESS_REMOVE_USER,
    SUCCESS_REMOVE_SELECTED_USERS,
    CONFIRMATION_REMOVE_USER,
    CONFIRMATION_REMOVE_SELECTED_USERS,
    ERROR_USER_EXISTS_BY_USERNAME,
    ERROR_USER_NOT_FOUND_BY_ID,
    ERROR_USER_NOT_FOUND,
    ERROR_DELETE_CURRENT_USER_FORBIDDEN,

    // Login
    CONFIRMATION_LOGOUT,

    // Payable
    ERROR_PAYABLE_NOT_FOUND_BY_ID,
    ERROR_PAYMENT_AMOUNT_GREATER_THAN_PAYABLE_AMOUNT,
    ERROR_INVALID_PAYMENT_DATE,
    ERROR_INVALID_AMOUNT,

    // Receivable
    ERROR_RECEIVABLE_NOT_FOUND_BY_ID,
    ERROR_PAYMENT_AMOUNT_GREATER_THAN_RECEIVABLE_AMOUNT,

    // Sale Report
    SUCCESS_EXPORT_SALE_REPORT,

    // Purchase Report
    SUCCESS_EXPORT_PURCHASE_REPORT,

    // Other
    CONFIRMATION_SEND_ERROR_REPORT,
    SUCCESS_SEND_ERROR_REPORT,
    ERROR_SEND_ERROR_REPORT,
    ERROR_REQUEST_PINODESK;

    @Override
    public String toString() {
        return this.name().toLowerCase();
    }

}
