create table if not exists drug_classification (
	id bigint not null auto_increment,
	created_at timestamp not null default current_timestamp,
	updated_at timestamp not null default current_timestamp on update current_timestamp,
	deleted_at timestamp,
	language_code char(2) not null,
	code varchar(64) not null,
	name varchar(256) not null,
	description varchar(512),
	primary key (id),
	index idx_drug_classification__deleted_at (deleted_at),
	index idx_drug_classification__code (code),
	index idx_drug_classification__code__deleted_at (code, deleted_at),
	index idx_drug_classification__language_code__code (language_code, code),
	index idx_drug_classification__language_code__code__deleted_at (language_code, code, deleted_at)
);

-- https://www.genome.jp/kegg-bin/get_htext?br08302.keg
-- https://www.verywellhealth.com/drug-classes-1123991
insert into drug_classification (id, created_at, updated_at, deleted_at, language_code, name, code) values
(null, current_timestamp, current_timestamp, null, 'en', 'Analgesics','0001'),
(null, current_timestamp, current_timestamp, null, 'en', 'Anesthetics','0002'),
(null, current_timestamp, current_timestamp, null, 'en', 'Anti-addiction agents','0003'),
(null, current_timestamp, current_timestamp, null, 'en', 'Antibacterials','0004'),
(null, current_timestamp, current_timestamp, null, 'en', 'Anticonvulsants','0005'),
(null, current_timestamp, current_timestamp, null, 'en', 'Antidementia agents','0006'),
(null, current_timestamp, current_timestamp, null, 'en', 'Antidepressants ','0007'),
(null, current_timestamp, current_timestamp, null, 'en', 'Antiemetics','0008'),
(null, current_timestamp, current_timestamp, null, 'en', 'Antifungals','0009'),
(null, current_timestamp, current_timestamp, null, 'en', 'Antigout agents','0010'),
(null, current_timestamp, current_timestamp, null, 'en', 'Anti-inflammatories','0011'),
(null, current_timestamp, current_timestamp, null, 'en', 'Antimigraine agents','0012'),
(null, current_timestamp, current_timestamp, null, 'en', 'Antimyasthenic agents','0013'),
(null, current_timestamp, current_timestamp, null, 'en', 'Antimycobacterials','0014'),
(null, current_timestamp, current_timestamp, null, 'en', 'Antineoplastics','0015'),
(null, current_timestamp, current_timestamp, null, 'en', 'Anti-obesity agents','0016'),
(null, current_timestamp, current_timestamp, null, 'en', 'Antiparasitics','0017'),
(null, current_timestamp, current_timestamp, null, 'en', 'Antiparkinson agents','0018'),
(null, current_timestamp, current_timestamp, null, 'en', 'Antipsychotics','0019'),
(null, current_timestamp, current_timestamp, null, 'en', 'Antispasticity agents','0020'),
(null, current_timestamp, current_timestamp, null, 'en', 'Antivirals','0021'),
(null, current_timestamp, current_timestamp, null, 'en', 'Anxiolytics','0022'),
(null, current_timestamp, current_timestamp, null, 'en', 'Bipolar agents','0023'),
(null, current_timestamp, current_timestamp, null, 'en', 'Blood glucose regulators','0024'),
(null, current_timestamp, current_timestamp, null, 'en', 'Blood products','0025'),
(null, current_timestamp, current_timestamp, null, 'en', 'Cardiovascular agents','0026'),
(null, current_timestamp, current_timestamp, null, 'en', 'Central nervous system agents','0027'),
(null, current_timestamp, current_timestamp, null, 'en', 'Contraceptives','0028'),
(null, current_timestamp, current_timestamp, null, 'en', 'Dental and oral agents','0029'),
(null, current_timestamp, current_timestamp, null, 'en', 'Dermatological agents','0030'),
(null, current_timestamp, current_timestamp, null, 'en', 'Electrolytes, minerals, metals, vitamins','0031'),
(null, current_timestamp, current_timestamp, null, 'en', 'Gastrointestinal agents','0032'),
(null, current_timestamp, current_timestamp, null, 'en', 'Genitourinary agents','0033'),
(null, current_timestamp, current_timestamp, null, 'en', 'Hormonal agents (adrenal)','0034'),
(null, current_timestamp, current_timestamp, null, 'en', 'Hormonal agents (pituitary)','0035'),
(null, current_timestamp, current_timestamp, null, 'en', 'Hormonal agents (prostaglandins)','0036'),
(null, current_timestamp, current_timestamp, null, 'en', 'Hormonal agents (sex hormones)','0037'),
(null, current_timestamp, current_timestamp, null, 'en', 'Hormonal agents (thyroid)','0038'),
(null, current_timestamp, current_timestamp, null, 'en', 'Hormone suppressant (adrenal)','0039'),
(null, current_timestamp, current_timestamp, null, 'en', 'Hormone suppressant (pituitary)','0040'),
(null, current_timestamp, current_timestamp, null, 'en', 'Hormone suppressant (thyroid)','0041'),
(null, current_timestamp, current_timestamp, null, 'en', 'Immunological agents','0042'),
(null, current_timestamp, current_timestamp, null, 'en', 'Infertility agents','0043'),
(null, current_timestamp, current_timestamp, null, 'en', 'Inflammatory bowel disease agents','0044'),
(null, current_timestamp, current_timestamp, null, 'en', 'Metabolic bone disease agents','0045'),
(null, current_timestamp, current_timestamp, null, 'en', 'Ophthalmic agents','0046'),
(null, current_timestamp, current_timestamp, null, 'en', 'Otic agents','0047'),
(null, current_timestamp, current_timestamp, null, 'en', 'Respiratory tract agents','0048'),
(null, current_timestamp, current_timestamp, null, 'en', 'Sexual disorder agents','0049'),
(null, current_timestamp, current_timestamp, null, 'en', 'Skeletal muscle relaxants','0050'),
(null, current_timestamp, current_timestamp, null, 'en', 'Sleep disorder agents','0051'),
(null, current_timestamp, current_timestamp, null, 'id', 'Analgesik','0001'),
(null, current_timestamp, current_timestamp, null, 'id', 'Anestesi','0002'),
(null, current_timestamp, current_timestamp, null, 'id', 'Anti-kecanduan','0003'),
(null, current_timestamp, current_timestamp, null, 'id', 'Antibakteri','0004'),
(null, current_timestamp, current_timestamp, null, 'id', 'Antikonvulsan','0005'),
(null, current_timestamp, current_timestamp, null, 'id', 'Antidemensia','0006'),
(null, current_timestamp, current_timestamp, null, 'id', 'Antidepresan ','0007'),
(null, current_timestamp, current_timestamp, null, 'id', 'Antiemetik','0008'),
(null, current_timestamp, current_timestamp, null, 'id', 'Antijamur','0009'),
(null, current_timestamp, current_timestamp, null, 'id', 'Antigout','0010'),
(null, current_timestamp, current_timestamp, null, 'id', 'Anti-inflamasi','0011'),
(null, current_timestamp, current_timestamp, null, 'id', 'Antimigrain','0012'),
(null, current_timestamp, current_timestamp, null, 'id', 'Antimiastenia','0013'),
(null, current_timestamp, current_timestamp, null, 'id', 'Antimikobakteri','0014'),
(null, current_timestamp, current_timestamp, null, 'id', 'Antineoplastik','0015'),
(null, current_timestamp, current_timestamp, null, 'id', 'Anti-obesitas','0016'),
(null, current_timestamp, current_timestamp, null, 'id', 'Antiparasit','0017'),
(null, current_timestamp, current_timestamp, null, 'id', 'Antiparkinson','0018'),
(null, current_timestamp, current_timestamp, null, 'id', 'Antipsikotik','0019'),
(null, current_timestamp, current_timestamp, null, 'id', 'Antispastisitas','0020'),
(null, current_timestamp, current_timestamp, null, 'id', 'Antivirus','0021'),
(null, current_timestamp, current_timestamp, null, 'id', 'Ansiolitik / Anticemas','0022'),
(null, current_timestamp, current_timestamp, null, 'id', 'Bipolar','0023'),
(null, current_timestamp, current_timestamp, null, 'id', 'Pengatur glukosa darah','0024'),
(null, current_timestamp, current_timestamp, null, 'id', 'Pengubah darah','0025'),
(null, current_timestamp, current_timestamp, null, 'id', 'Kardiovaskular','0026'),
(null, current_timestamp, current_timestamp, null, 'id', 'Sistem saraf pusat','0027'),
(null, current_timestamp, current_timestamp, null, 'id', 'Kontrasepsi','0028'),
(null, current_timestamp, current_timestamp, null, 'id', 'Gigi dan mulut','0029'),
(null, current_timestamp, current_timestamp, null, 'id', 'Dermatologis','0030'),
(null, current_timestamp, current_timestamp, null, 'id', 'Elektrolit, mineral, logam, vitamin','0031'),
(null, current_timestamp, current_timestamp, null, 'id', 'Gastrointestinal','0032'),
(null, current_timestamp, current_timestamp, null, 'id', 'Genitourinari','0033'),
(null, current_timestamp, current_timestamp, null, 'id', 'Hormonal (adrenal)','0034'),
(null, current_timestamp, current_timestamp, null, 'id', 'Hormonal (pituitary)','0035'),
(null, current_timestamp, current_timestamp, null, 'id', 'Hormonal (prostaglandin)','0036'),
(null, current_timestamp, current_timestamp, null, 'id', 'Hormonal (hormon sex)','0037'),
(null, current_timestamp, current_timestamp, null, 'id', 'Hormonal (tiroid)','0038'),
(null, current_timestamp, current_timestamp, null, 'id', 'Penekan hormon (adrenal)','0039'),
(null, current_timestamp, current_timestamp, null, 'id', 'Penekan hormon (pituitary)','0040'),
(null, current_timestamp, current_timestamp, null, 'id', 'Penekan hormon (tiroid)','0041'),
(null, current_timestamp, current_timestamp, null, 'id', 'Imunologi','0042'),
(null, current_timestamp, current_timestamp, null, 'id', 'Infertilitas','0043'),
(null, current_timestamp, current_timestamp, null, 'id', 'Penyakit radang usus','0044'),
(null, current_timestamp, current_timestamp, null, 'id', 'Penyakit tulang metabolik','0045'),
(null, current_timestamp, current_timestamp, null, 'id', 'Ophtal (mata)','0046'),
(null, current_timestamp, current_timestamp, null, 'id', 'Otic (telinga)','0047'),
(null, current_timestamp, current_timestamp, null, 'id', 'Saluran pernafasan','0048'),
(null, current_timestamp, current_timestamp, null, 'id', 'Gangguan seksual','0049'),
(null, current_timestamp, current_timestamp, null, 'id', 'Relaksan otot rangka','0050'),
(null, current_timestamp, current_timestamp, null, 'id', 'Gangguan tidur','0051');
