create table if not exists product (
	id bigint not null auto_increment,
	created_at timestamp not null default current_timestamp,
	updated_at timestamp not null default current_timestamp on update current_timestamp,
	deleted_at timestamp,
	code varchar(64) not null,
	barcode varchar(24),
	name varchar(256) not null,
	description varchar(512),
	quantity integer null,
	unit_id bigint not null,
	unit_label varchar(32) not null,
	category_code varchar(64) not null,
	general_selling_price decimal(12,2) null,
	prescription_selling_price decimal(12,2) null,
    average_buying_price decimal(12,2) null,
	closest_expired_date date null,
	status varchar(8) not null, -- active, inactive
	primary key (id),
	constraint fk_product__unit_id foreign key (unit_id) references unit(id),
	index idx_product__deleted_at (deleted_at),
	index idx_product__code (code),
	index idx_product__barcode (barcode),
	index idx_product__category_code (category_code),
	index idx_product__id__unit_id (id, unit_id)
);
