create table if not exists product_stock (
	id bigint not null auto_increment,
	created_at timestamp not null default current_timestamp,
	updated_at timestamp not null default current_timestamp on update current_timestamp,
	deleted_at timestamp,
	product_id bigint not null,
	quantity_in int,
	quantity_out int,
	final_quantity int not null,
	purchase_id bigint,
	purchase_invoice_number varchar(64),
	sale_id bigint,
	sale_invoice_number varchar(64),
	user_id bigint not null,
	activity varchar(128) not null,
	remarks varchar(128),
	primary key (id),
	index idx_product_stock__deleted_at (deleted_at),
	index idx_product_stock__product_id (product_id),
	index idx_product_stock__product_id__deleted_at (product_id, deleted_at),
	index idx_product_stock__purchase_id (purchase_id),
	index idx_product_stock__purchase_id__deleted_at (purchase_id, deleted_at),
	index idx_product_stock__sale_id (sale_id),
	index idx_product_stock__sale_id__deleted_at (sale_id, deleted_at),
	index idx_product_stock__user_id (user_id),
	index idx_product_stock__user_id__deleted_at (user_id, deleted_at),
	constraint fk_product_stock__product_id foreign key (product_id) references product(id),
	constraint fk_product_stock__purchase_id foreign key (purchase_id) references purchase(id)
);
