create table if not exists doctor_category (
	id bigint not null auto_increment,
	created_at timestamp not null default current_timestamp,
	updated_at timestamp not null default current_timestamp on update current_timestamp,
	deleted_at timestamp,
	language char(2) not null,
	code char(4) not null,
	name varchar(256) not null,
	primary key (id),
	index idx_doctor_category__deleted_at (deleted_at),
	index idx_doctor_category__code (code),
	index idx_doctor_category__code__deleted_at (code, deleted_at),
	index idx_doctor_category__language__code (language, code),
	index idx_doctor_category__language__code__deleted_at (language, code, deleted_at)
);

create table if not exists doctor (
	id bigint not null auto_increment,
	created_at timestamp not null default current_timestamp,
	updated_at timestamp not null default current_timestamp on update current_timestamp,
	deleted_at timestamp,
	code varchar(12) not null, -- e.g. 202103110001
	category_code char(4) not null,
	name varchar(256) not null,
	registration_number varchar(16),
	medical_license_number varchar(256),
	primary key (id),
	index idx_doctor__deleted_at (deleted_at),
	index idx_doctor__code (code),
	index idx_doctor__code__deleted_at (code, deleted_at),
	index idx_doctor__category_code (category_code),
	index idx_doctor__category_code__deleted_at (category_code, deleted_at)
);

insert into doctor_category (id, created_at, updated_at, deleted_at, language, code, name) values
(null, current_timestamp, current_timestamp, null, 'en', '0001', 'General Practitioner'),
(null, current_timestamp, current_timestamp, null, 'id', '0001', 'Dokter Umum'),
(null, current_timestamp, current_timestamp, null, 'en', '0002', 'Dentist'),
(null, current_timestamp, current_timestamp, null, 'id', '0002', 'Dokter Gigi'),
(null, current_timestamp, current_timestamp, null, 'en', '0003', 'Pediatric'),
(null, current_timestamp, current_timestamp, null, 'id', '0003', 'Dokter Spesialis Anak (Sp.A)'),
(null, current_timestamp, current_timestamp, null, 'en', '0004', 'Andrologist'),
(null, current_timestamp, current_timestamp, null, 'id', '0004', 'Dokter Spesialis Andrologi (Sp.And)'),
(null, current_timestamp, current_timestamp, null, 'en', '0005', 'Anesthesiologist and Intensive Therapist'),
(null, current_timestamp, current_timestamp, null, 'id', '0005', 'Dokter Spesialis Anestesiologi dan Terapi Intensif (Sp.An)'),
(null, current_timestamp, current_timestamp, null, 'en', '0006', 'Medical Acupuncture'),
(null, current_timestamp, current_timestamp, null, 'id', '0006', 'Dokter Spesialis Akupunktur Medik (Sp.Ak)'),
(null, current_timestamp, current_timestamp, null, 'en', '0007', 'Surgeon'),
(null, current_timestamp, current_timestamp, null, 'id', '0007', 'Dokter Spesialis Bedah (Sp.B)'),
(null, current_timestamp, current_timestamp, null, 'en', '0008', 'Pedriatic Surgeon'),
(null, current_timestamp, current_timestamp, null, 'id', '0008', 'Dokter Spesialis Bedah Anak (Sp.BA)'),
(null, current_timestamp, current_timestamp, null, 'en', '0009', 'Plastic, Reconstructive and Aesthetic Surgeon'),
(null, current_timestamp, current_timestamp, null, 'id', '0009', 'Dokter Spesialis Bedah Plastik, Rekonstruksi, dan Estetik (Sp.BP-RE)'),
(null, current_timestamp, current_timestamp, null, 'en', '0010', 'Thoracic, Cardiac and Vascular Surgeon'),
(null, current_timestamp, current_timestamp, null, 'id', '0010', 'Dokter Spesialis Bedah Toraks, Kardiak dan Vaskular (Sp.BTKV)'),
(null, current_timestamp, current_timestamp, null, 'en', '0011', 'Dermatologist and Venereologist'),
(null, current_timestamp, current_timestamp, null, 'id', '0011', 'Dokter Spesialis Dermatologi dan Venereologi (Sp.DV)'),
(null, current_timestamp, current_timestamp, null, 'en', '0012', 'Emergency Medicine'),
(null, current_timestamp, current_timestamp, null, 'id', '0012', 'Dokter Spesialis Kegawatdaruratan Medik (Sp.EM)'),
(null, current_timestamp, current_timestamp, null, 'en', '0013', 'Clinical Pharmacologist'),
(null, current_timestamp, current_timestamp, null, 'id', '0013', 'Dokter Spesialis Farmakologi Klinik (Sp.FK)'),
(null, current_timestamp, current_timestamp, null, 'en', '0014', 'Forensic and Medicolegal'),
(null, current_timestamp, current_timestamp, null, 'id', '0014', 'Dokter Spesialis Forensik dan Medikolegal (Sp.FM)'),
(null, current_timestamp, current_timestamp, null, 'en', '0015', 'Clinical Nutritionist'),
(null, current_timestamp, current_timestamp, null, 'id', '0015', 'Dokter Spesialis Gizi Klinik (Sp.GK)'),
(null, current_timestamp, current_timestamp, null, 'en', '0016', 'Cardiologist'),
(null, current_timestamp, current_timestamp, null, 'id', '0016', 'Dokter Spesialis Jantung dan Pembuluh Darah (Sp.JP)'),
(null, current_timestamp, current_timestamp, null, 'en', '0017', 'Physical Medicine and Rehabilitation'),
(null, current_timestamp, current_timestamp, null, 'id', '0017', 'Dokter Spesialis Kedokteran Fisik dan Rehabilitasi (Sp.KFR)'),
(null, current_timestamp, current_timestamp, null, 'en', '0018', 'Psychiatrist'),
(null, current_timestamp, current_timestamp, null, 'id', '0018', 'Dokter Spesialis Kedokteran Jiwa (Sp.KJ)'),
(null, current_timestamp, current_timestamp, null, 'en', '0019', 'Marine Medicine'),
(null, current_timestamp, current_timestamp, null, 'id', '0019', 'Dokter Spesialis Kedokteran Kelautan (Sp.KL)'),
(null, current_timestamp, current_timestamp, null, 'en', '0020', 'Primary Service Family Medicine'),
(null, current_timestamp, current_timestamp, null, 'id', '0020', 'Dokter Spesialis Kedokteran Keluarga Layanan Primer (Sp.DLP)'),
(null, current_timestamp, current_timestamp, null, 'en', '0021', 'Nuclear Medicine and Molecular Therapists'),
(null, current_timestamp, current_timestamp, null, 'id', '0021', 'Dokter Spesialis Kedokteran Nuklir dan Teranostik Molekuler (Sp.KN)'),
(null, current_timestamp, current_timestamp, null, 'en', '0022', 'Occupational Medicine'),
(null, current_timestamp, current_timestamp, null, 'id', '0022', 'Dokter Spesialis Kedokteran Okupasi (Sp.Ok)'),
(null, current_timestamp, current_timestamp, null, 'en', '0023', 'Sports Medicine'),
(null, current_timestamp, current_timestamp, null, 'id', '0023', 'Dokter Spesialis Kedokteran Olahraga (Sp.KO)'),
(null, current_timestamp, current_timestamp, null, 'en', '0024', 'Aviation Medicine'),
(null, current_timestamp, current_timestamp, null, 'id', '0024', 'Dokter Spesialis Kedokteran Penerbangan (Sp.KP)'),
(null, current_timestamp, current_timestamp, null, 'en', '0025', 'Clinical Microbiologist'),
(null, current_timestamp, current_timestamp, null, 'id', '0025', 'Dokter Spesialis Mikrobiologi Klinik (Sp.MK)'),
(null, current_timestamp, current_timestamp, null, 'en', '0026', 'Neurologist'),
(null, current_timestamp, current_timestamp, null, 'id', '0026', 'Dokter Spesialis Neurologi (Sp.N)'),
(null, current_timestamp, current_timestamp, null, 'en', '0027', 'Obstetrician and Gynecologist'),
(null, current_timestamp, current_timestamp, null, 'id', '0027', 'Dokter Spesialis Obstetri dan Ginekologi (Sp.OG)'),
(null, current_timestamp, current_timestamp, null, 'en', '0028', 'Ophthalmologist'),
(null, current_timestamp, current_timestamp, null, 'id', '0028', 'Dokter Spesialis Oftalmologi (Mata) (Sp.M)'),
(null, current_timestamp, current_timestamp, null, 'en', '0029', 'Radiation Oncologist'),
(null, current_timestamp, current_timestamp, null, 'id', '0029', 'Dokter Spesialis Onkologi Radiasi (Sp.Onk.Rad)'),
(null, current_timestamp, current_timestamp, null, 'en', '0030', 'Orthopedic and Traumatologist'),
(null, current_timestamp, current_timestamp, null, 'id', '0030', 'Dokter Spesialis Orthopaedi dan Traumatologi (Sp.OT)'),
(null, current_timestamp, current_timestamp, null, 'en', '0031', 'Clinical Parasitologist'),
(null, current_timestamp, current_timestamp, null, 'id', '0031', 'Dokter Spesialis Parasitologi Klinik (Sp.ParK)'),
(null, current_timestamp, current_timestamp, null, 'en', '0032', 'Anatomical Pathologist'),
(null, current_timestamp, current_timestamp, null, 'id', '0032', 'Dokter Spesialis Patologi Anatomi (Sp.PA)'),
(null, current_timestamp, current_timestamp, null, 'en', '0033', 'Clinical Pathologist'),
(null, current_timestamp, current_timestamp, null, 'id', '0033', 'Dokter Spesialis Patologi Klinik (Sp.PK)'),
(null, current_timestamp, current_timestamp, null, 'en', '0034', 'Internist'),
(null, current_timestamp, current_timestamp, null, 'id', '0034', 'Dokter Spesialis Penyakit Dalam (Sp.PD)'),
(null, current_timestamp, current_timestamp, null, 'en', '0035', 'Radiologist'),
(null, current_timestamp, current_timestamp, null, 'id', '0035', 'Dokter Spesialis Radiologi (Sp.Rad)'),
(null, current_timestamp, current_timestamp, null, 'en', '0036', 'Ear Nose Throat (ENT) Head Neck Surgeon'),
(null, current_timestamp, current_timestamp, null, 'id', '0036', 'Dokter Spesialis Telinga Hidung Tenggorok (THT) Bedah Kepala Leher (Sp.THT-KL)'),
(null, current_timestamp, current_timestamp, null, 'en', '0037', 'Urologist'),
(null, current_timestamp, current_timestamp, null, 'id', '0037', 'Dokter Spesialis Urologi (Sp.U)'),
(null, current_timestamp, current_timestamp, null, 'en', '0038', 'Oral and Maxillofacial Surgeon'),
(null, current_timestamp, current_timestamp, null, 'id', '0038', 'Dokter Spesialis Bedah Mulut dan Maksilofasial (Sp.BM)'),
(null, current_timestamp, current_timestamp, null, 'en', '0039', 'Pediatric Dentist / Pedodontist'),
(null, current_timestamp, current_timestamp, null, 'id', '0039', 'Dokter Spesialis Kedokteran Gigi Anak (Sp.KGA)'),
(null, current_timestamp, current_timestamp, null, 'en', '0040', 'Endodontist'),
(null, current_timestamp, current_timestamp, null, 'id', '0040', 'Dokter Spesialis Konservasi Gigi (Sp.KG)'),
(null, current_timestamp, current_timestamp, null, 'en', '0041', 'Oral Medicine'),
(null, current_timestamp, current_timestamp, null, 'id', '0041', 'Dokter Spesialis Penyakit Mulut (Sp.PM)'),
(null, current_timestamp, current_timestamp, null, 'en', '0042', 'Orthodontist'),
(null, current_timestamp, current_timestamp, null, 'id', '0042', 'Dokter Spesialis Ortodonsia (Sp.Ort)'),
(null, current_timestamp, current_timestamp, null, 'en', '0043', 'Periodontist'),
(null, current_timestamp, current_timestamp, null, 'id', '0043', 'Dokter Spesialis Periodonsia (Sp.Perio)'),
(null, current_timestamp, current_timestamp, null, 'en', '0044', 'Prosthodontist'),
(null, current_timestamp, current_timestamp, null, 'id', '0044', 'Dokter Spesialis Prostodonsia (Sp.Pros)'),
(null, current_timestamp, current_timestamp, null, 'en', '0045', 'Oral and Maxillofacial Radiologist'),
(null, current_timestamp, current_timestamp, null, 'id', '0045', 'Dokter Spesialis Radiologi Kedokteran Gigi (Sp.RKG)'),
(null, current_timestamp, current_timestamp, null, 'en', '0046', 'Forensic Odontologist'),
(null, current_timestamp, current_timestamp, null, 'id', '0046', 'Dokter Spesialis Odontologi Forensik (Sp.OF)');
